apiVersion: v1
kind: Service
metadata:
  name: capstone-bg-lb
  labels:
    app: capstone-bg-lb
spec:
  selector:
    app: blue
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  type: LoadBalancer

